// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_V1eVnz8hGpZMG1d4OvWanhb0UVaZbTE',
    appId: '1:780764168757:web:a370c3408b4c2ebefd677c',
    messagingSenderId: '780764168757',
    projectId: 'thimar-driver-21242',
    authDomain: 'thimar-driver-21242.firebaseapp.com',
    storageBucket: 'thimar-driver-21242.appspot.com',
    measurementId: 'G-KV9H3H82J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0AL6y6YKMxBv351KW1W41wMR3iob9Lxg',
    appId: '1:780764168757:android:06b2e3a7583c4979fd677c',
    messagingSenderId: '780764168757',
    projectId: 'thimar-driver-21242',
    storageBucket: 'thimar-driver-21242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjN6-I-RLFKfUF_VHOgG-nyQROKk6YsA',
    appId: '1:780764168757:ios:91162b64c88dc1d1fd677c',
    messagingSenderId: '780764168757',
    projectId: 'thimar-driver-21242',
    storageBucket: 'thimar-driver-21242.appspot.com',
    iosBundleId: 'com.alalmiya.thimarDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnjN6-I-RLFKfUF_VHOgG-nyQROKk6YsA',
    appId: '1:780764168757:ios:ada4a7809b1791d3fd677c',
    messagingSenderId: '780764168757',
    projectId: 'thimar-driver-21242',
    storageBucket: 'thimar-driver-21242.appspot.com',
    iosBundleId: 'com.alalmiya.thimarDriver.RunnerTests',
  );
}
